version: '2.2'
services:
  springboot:
    image: 172.31.46.186:8084/spring:10
    container_name: springboot
    ports:
     - "8080:8080"
    networks:
      - javahome-app
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - javahome-app
    volumes:
      - muni:/data/db
networks:
  javahome-app:
    driver: bridge 
volumes:
   muni:
     external: true
